title: "Javad Taba Blog"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  entries:
    output: true
    permalink: /:collection/:name/